name: Deploy React demo

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install & build
        run: |
          yarn install --frozen-lockfile
          yarn lerna run build --scope @matrices/react --include-dependencies

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: packages/frontend-react/build